### ISSUE TITLE
The QA confidence score by your script

### ISSUE THREAD

**Issue by kenchan0226** [recitalAI/summa-qa#1]
Hi, thanks for the nice work. I have a question about the QA confidence score. 
According to your paper, the QA confidence score should be the probability of the
true answer according to the QA model. However, in the predict function of qa_models.py of your source code, the prob is the probability of the *predicted answer. I wonder which definition of QA confidence score should we use?

**Comment by stjaco** [comment]
Hi, it is the probability of the predicted answer.

In the paper we wrote: "Complementary to the F1 score, we propose to also consider the confidence of the QA system for its retrieved answer. This corresponds, for each triplet, to the probability of the true answer according to the QA model."

The formulation of the last sentence is probably confusing, it should rather read "This corresponds, for each triplet, to the probability - according to the QA model - of the predicted answer to be correct."

**Comment by kenchan0226** [comment]
Thanks!
